name: Build project

on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pillow

    - name: Download ZGB-Linux-x64
      run: wget https://github.com/gbdk-2020/CrossZGB/releases/download/v2025.0/ZGB-Linux-x64.tar.gz

    - name: Unpack ZGB-Linux-x64
      run: |
        tar -xzf ZGB-Linux-x64.tar.gz
        echo "GBDK_HOME=$(pwd)/CrossZGB/gbdk" >> $GITHUB_ENV
        echo "ZGB_PATH=$(pwd)/CrossZGB/ZGB/common" >> $GITHUB_ENV

    - name: Build project
      run: |
        cd src
        make
      env:
        GBDK_HOME: ${{ env.GBDK_HOME }}
        ZGB_PATH: ${{ env.ZGB_PATH }}

    - name: Run custom logo tool
      run: npx -y @joshbalfour/gb-custom-logo@latest

    - name: Build and run insidegadgets logo appender
      run: |
        cd logo-appender
        make
        cd ../
        ./logo-appender/custom_logo_appender_v1.0 ./bin/gbc/PACKS.gbc ./bin/gbc/PACKS.patched.gbc

    - name: Upload build artifacts
      uses: christopherhx/gitea-upload-artifact@v4
      with:
        name: ROM-files
        path: bin/gbc/*.gbc